name: matule_me_3
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  dotted_line: ^3.2.3
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  flutter_svg: ^2.0.17
  get_it: ^8.0.3
  go_router: ^14.8.0
  google_fonts: ^6.2.1
  otp_pin_field: ^1.4.0
  shared_preferences: ^2.5.2
  supabase_flutter: ^2.8.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
